const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=67',
  'https://sanand0.github.io/tdsdata/js_table/?seed=68',
  'https://sanand0.github.io/tdsdata/js_table/?seed=69',
  'https://sanand0.github.io/tdsdata/js_table/?seed=70',
  'https://sanand0.github.io/tdsdata/js_table/?seed=71',
  'https://sanand0.github.io/tdsdata/js_table/?seed=72',
  'https://sanand0.github.io/tdsdata/js_table/?seed=73',
  'https://sanand0.github.io/tdsdata/js_table/?seed=74',
  'https://sanand0.github.io/tdsdata/js_table/?seed=75',
  'https://sanand0.github.io/tdsdata/js_table/?seed=76',
];

(async () => {
  // Launch a headless (invisible) browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url);

    // Wait for the table to load (it's dynamically generated by JavaScript)
    await page.waitForSelector('table');

    // Grab all cell text inside the table
    const numbers = await page.$$eval('table td', cells =>
      cells
        .map(cell => parseFloat(cell.innerText))
        .filter(n => !isNaN(n))  // keep only actual numbers
    );

    const pageSum = numbers.reduce((a, b) => a + b, 0);
    console.log(`Seed ${url.split('seed=')[1]}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`\nTotal sum across all pages: ${grandTotal}`);

  await browser.close();
})();
